package sv.edu.udb.hibernate;
// Generated 10-21-2021 03:56:51 AM by Hibernate Tools 4.3.1
/**
 * Datosempleados generated by hbm2java
 */
public class Datosempleados  implements java.io.Serializable {


     private Integer id;
     private String nombres;
     private String apellidos;
     private String sexo;
     private Integer edad;
     private String telefono;
     private String direccion;

    public Datosempleados() {
    }

    public Datosempleados(String nombres, String apellidos, String sexo, Integer edad, String telefono, String direccion) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.sexo = sexo;
       this.edad = edad;
       this.telefono = telefono;
       this.direccion = direccion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

}


